public class AddressStrictnessWrapper 
{
    public Boolean hideReturnAddressUS{get;set;}
    public Boolean liveApproved{get;set;}
    public Boolean hideReturnAddressUK{get;set;}
    public String name{get;set;}
    public String externalPaymentMethod{get;set;}
    public Boolean sameDaySLA{get;set;}
    public Boolean enforcePlanLimits{get;set;}
    public Integer spend{get;set;}
    public String countryCode{get;set;}
    public Boolean sso{get;set;}
    public Integer chequeNumber{get;set;}
    public String stripeCustomer{get;set;}
    public Boolean allowInvitingUsersWithoutSubscribing{get;set;}
    public Integer usage{get;set;}
    public String addressStrictness{get;set;}
    public String createdAt{get;set;}
    public String updatedAt{get;set;}
    public String id{get;set;}
    
}